spotify_username: "pleasehlep"
spotify_client_id: "595d68968e1b4c62b0e8bc2a07c707d8"
spotify_client_secret: "1ad58ac0f7834d68b5d50238f5357b3c"
spotify_playlist_id: "7oVvzGTHlAbixI9DDx0PNd"
spotify_redirect_uri: "http://127.0.0.1/callback/"
discogs_consumer_key: "hfjoMiQutxhAanjDmJpA"
discogs_consumer_secret: "EhOHKTfbulkFamYBQQhvyiajpuAJypnH"
discogs_user_token: "japsIzhsDnbqTotyejLqFyGurlBLgpeFqEIfhgHd"
discogs_redirect_uri: "http://127.0.0.1/callback/"
spotify_app_url: "https://developer.spotify.com/dashboard/applications/595d68968e1b4c62b0e8bc2a07c707d8"
discogs_app_url: "https://www.discogs.com/applications/edit/21436"